#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: http://www.l10n.cz
baseurl: ""
title: Překladatelská komunita L10N.cz
description: Překládáme svobodný a otevřený software.
avatar: /assets/img/logo.png
language: cs
favicon: /favicon.ico

#
# Icons
#
icons:
  rss: true
  email: diskuze@lists.l10n.cz
  github: l10ncz/l10ncz
  bitbucket:
  twitter:
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: # e.g. UA-000000-01
disqus:

#
# Localizations.
#
str_next: Následující
str_prev: Předchozí
str_read_more: Více...
str_search: Hledat
str_recent_posts: Nedávné příspěvky
str_show_all_posts: Zobrazit všechny příspěvky

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: false
  facebook: false   # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url:
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
remote_theme: ttskch/jekyll-ttskch-theme
gems:
  - jekyll-paginate

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - assets/l10n-slovnik
